# The prefix used for all commands.
prefix = "-"
# A list of Discord IDs to use as owners. This will grant you access to commands such as jishaku.
owners = [215290701913653248]
# A list of cogs that will be loaded when the bot has started.
cogs = ["cogs.help", "cogs.jeopardy", "cogs.error", "cogs.moderation", "cogs.fun"]

[resources]
# The path to various resources from the src folder
jeopardy_questions = "res/jeopardy.json"

[colors]
# The color for the embeds sent by the bot.
default = 0xFEE75C
moderation = 0xED2828
error = 0xED2828
games = 0x316FB8

[icons]
error = "https://cdn.discordapp.com/attachments/953132947874148403/953365026411012166/Error.png"
moderation = "https://media.discordapp.net/attachments/953132947874148403/953365027363094579/Moderation.png"
